[package]
name = "zed-pest"
version = "0.1.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
