id = "pest"
name = "Pest"
description = "Pest parser language support for Zed"
version = "0.1.1"
schema_version = 1
authors = ["Jason Lee <huacnlee@gmail.com>"]
repository = "https://github.com/pest-parser/zed-pest"

[language_servers.pest]
name = "Pest Language Server"
language = "Pest"

[grammars.pest]
repository = "https://github.com/pest-parser/tree-sitter-pest"
commit = "a8a98a824452b1ec4da7f508386a187a2f234b85"
